services:
  db:
    image: postgres:15-alpine
    container_name: planets_db
    environment:
      POSTGRES_DB: ntd_django_db
      POSTGRES_USER: ntd_user
      POSTGRES_PASSWORD: ntd_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ntd_user -d ntd_django_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: planets_api
    command: >
      sh -c "
        while ! nc -z db 5432; do sleep 1; done &&
        python manage.py makemigrations --noinput &&
        python manage.py migrate --noinput &&
        python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - ./django_crud:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - PLANETS_URL=https://swapi-graphql.netlify.app/graphql?query=query+Query+%7BallPlanets%7Bplanets%7Bname+population+terrains+climates%7D%7D%7D
      - DATABASE_ENGINE=django.db.backends.postgresql
      - DATABASE_NAME=ntd_django_db
      - DATABASE_USER=ntd_user
      - DATABASE_PASSWORD=ntd_password
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
